public with sharing class IterationRecipes {

    private Account account = null;

    public static List<String> iterableApiClientRecipe() {
        List<String> records = new List<String>();
        return records;
    } 

    private string anotheraccount {
        get{
            //this.account = 'test';
            //return this.propertyVal;
        }
        set;
    }

    public static ArrayList<String> iterableApiClientRecipe() {
        // Some some = null;
        return null;
    }

    public static ArrayList<Integer> iterableApiClientRecipe( Set<String> set ) {
        return null;
    }
}
